name: Upstream Sync

permissions:
  contents: write

on:
  workflow_dispatch: # 仅手动触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6

      - name: Sync upstream changes
        uses: aormsby/fork-sync-with-upstream-action@v3.4.3
        with:
          upstream_sync_repo: cmliu/edgetunnel
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
